# External funding platforms
github: [nejcm]
# patreon: USERNAME
# open_collective: USERNAME
# ko_fi: USERNAME
# tidelift: PLATFORM-NAME/PACKAGE-NAME
# community_bridge: PROJECT-NAME
# liberapay: USERNAME
# issuehunt: USERNAME
# polar: USERNAME
# buy_me_a_coffee: USERNAME
thanks_dev: u/gh/nejcm

# Custom sponsorship URLs
# custom: ["https://example.com/sponsor"]
