import type { SimpleIcon } from 'simple-icons';
import {
  siAdidas,
  siAfterpay,
  siAirbnb,
  siAlbertheijn,
  siAldinord,
  siAliexpress,
  siAmericanexpress,
  siAnthropic,
  siApplepay,
  siAppletv,
  siAsda,
  siAtandt,
  siAudible,
  siBookingdotcom,
  siBurgerking,
  siCarrefour,
  siClaude,
  siCoinbase,
  siCrunchyroll,
  siDazn,
  siDeepseek,
  siDeezer,
  siDeliveroo,
  siDelta,
  siDeutschebahn,
  siDeutschetelekom,
  siDm,
  siDoordash,
  siDropbox,
  siDuolingo,
  siEbay,
  siEdeka,
  siEmirates,
  siEpicgames,
  siEtsy,
  siExpedia,
  siFoodpanda,
  siGithubcopilot,
  siGlovo,
  siGooglegemini,
  siGooglepay,
  siGrab,
  siGumroad,
  siHandm,
  siHbomax,
  siHellofresh,
  siHuggingface,
  siIkea,
  siInstacart,
  siJusteat,
  siKaufland,
  siKfc,
  siKlarna,
  siLidl,
  siLufthansa,
  siLyft,
  siMcdonalds,
  siMonzo,
  siMorrisons,
  siMovistar,
  siN26,
  siNetflix,
  siNike,
  siNotion,
  siO2,
  siOpenrouter,
  siParamountplus,
  siPatreon,
  siPaypal,
  siPeloton,
  siPenny,
  siPerplexity,
  siPicnic,
  siPlaystation,
  siPostmates,
  siRakuten,
  siRevolut,
  siRewe,
  siRossmann,
  siRyanair,
  siShell,
  siSouthwestairlines,
  siSpotify,
  siStarbucks,
  siStarlingbank,
  siSteam,
  siStripe,
  siTacobell,
  siTarget,
  siTelefonica,
  siTesco,
  siTesla,
  siTidal,
  siTwitch,
  siUber,
  siUbereats,
  siUniqlo,
  siUnitedairlines,
  siVenmo,
  siVerizon,
  siVinted,
  siVodafone,
  siWesternunion,
  siWise,
  siYoutube,
  siZalando,
  siZelle,
} from 'simple-icons';

type InferInput = {
  merchant_name?: string | null;
  note?: string | null;
};

export const MerchantsMap: Dict<{ contains: string[]; icon: SimpleIcon }> = {
  adidas: { contains: ['adidas'], icon: siAdidas },
  afterpay: { contains: ['afterpay'], icon: siAfterpay },
  airbnb: { contains: ['airbnb', 'air bnb'], icon: siAirbnb },
  albertheijn: { contains: ['albert heijn', 'ah.nl'], icon: siAlbertheijn },
  aldinord: { contains: ['aldi'], icon: siAldinord },
  aliexpress: { contains: ['aliexpress', 'ali express'], icon: siAliexpress },
  americanexpress: { contains: ['american express', 'amex '], icon: siAmericanexpress },
  anthropic: { contains: ['anthropic'], icon: siAnthropic },
  applepay: { contains: ['apple pay'], icon: siApplepay },
  appletv: { contains: ['apple tv'], icon: siAppletv },
  asda: { contains: ['asda'], icon: siAsda },
  atandt: { contains: ['at&t', 'at and t', 'att mobility', 'att payment'], icon: siAtandt },
  audible: { contains: ['audible'], icon: siAudible },
  bookingdotcom: { contains: ['booking.com', 'booking com'], icon: siBookingdotcom },
  burgerking: { contains: ['burger king', 'burgerking'], icon: siBurgerking },
  carrefour: { contains: ['carrefour'], icon: siCarrefour },
  claude: { contains: ['claude'], icon: siClaude },
  coinbase: { contains: ['coinbase'], icon: siCoinbase },
  crunchyroll: { contains: ['crunchyroll'], icon: siCrunchyroll },
  dazn: { contains: ['dazn'], icon: siDazn },
  deepseek: { contains: ['deepseek'], icon: siDeepseek },
  deezer: { contains: ['deezer'], icon: siDeezer },
  deliveroo: { contains: ['deliveroo'], icon: siDeliveroo },
  delta: { contains: ['delta air'], icon: siDelta },
  deutschebahn: { contains: ['deutsche bahn', 'db vertrieb', 'bahn.de'], icon: siDeutschebahn },
  deutschetelekom: { contains: ['deutsche telekom', 'telekom shop'], icon: siDeutschetelekom },
  dm: { contains: ['dm-drogerie', 'dm drogerie', 'dm markt'], icon: siDm },
  doordash: { contains: ['doordash', 'door dash'], icon: siDoordash },
  dropbox: { contains: ['dropbox'], icon: siDropbox },
  duolingo: { contains: ['duolingo'], icon: siDuolingo },
  ebay: { contains: ['ebay'], icon: siEbay },
  edeka: { contains: ['edeka'], icon: siEdeka },
  emirates: { contains: ['emirates'], icon: siEmirates },
  epicgames: { contains: ['epic games', 'fortnite'], icon: siEpicgames },
  etsy: { contains: ['etsy'], icon: siEtsy },
  expedia: { contains: ['expedia'], icon: siExpedia },
  foodpanda: { contains: ['foodpanda', 'food panda'], icon: siFoodpanda },
  githubcopilot: { contains: ['github copilot', 'copilot pro'], icon: siGithubcopilot },
  glovo: { contains: ['glovo'], icon: siGlovo },
  googlegemini: { contains: ['google gemini', 'gemini advanced', 'gemini ultra'], icon: siGooglegemini },
  googlepay: { contains: ['google pay', 'gpay'], icon: siGooglepay },
  grab: { contains: ['grab'], icon: siGrab },
  gumroad: { contains: ['gumroad'], icon: siGumroad },
  handm: { contains: ['h&m', 'h & m', 'hm.com'], icon: siHandm },
  hbomax: { contains: ['hbo max', 'hbomax'], icon: siHbomax },
  hellofresh: { contains: ['hello fresh', 'hellofresh'], icon: siHellofresh },
  huggingface: { contains: ['hugging face', 'huggingface'], icon: siHuggingface },
  ikea: { contains: ['ikea'], icon: siIkea },
  instacart: { contains: ['instacart'], icon: siInstacart },
  justeat: { contains: ['just eat', 'justeat'], icon: siJusteat },
  kaufland: { contains: ['kaufland'], icon: siKaufland },
  kfc: { contains: ['kfc'], icon: siKfc },
  klarna: { contains: ['klarna'], icon: siKlarna },
  lidl: { contains: ['lidl'], icon: siLidl },
  lufthansa: { contains: ['lufthansa'], icon: siLufthansa },
  lyft: { contains: ['lyft'], icon: siLyft },
  mcdonalds: { contains: ['mcdonalds', 'mcdonald'], icon: siMcdonalds },
  monzo: { contains: ['monzo'], icon: siMonzo },
  morrisons: { contains: ['morrisons'], icon: siMorrisons },
  movistar: { contains: ['movistar'], icon: siMovistar },
  n26: { contains: ['n26'], icon: siN26 },
  netflix: { contains: ['netflix', 'nflx'], icon: siNetflix },
  nike: { contains: ['nike'], icon: siNike },
  notion: { contains: ['notion'], icon: siNotion },
  o2: { contains: ['o2 shop', 'o2.de', 'telefónica o2', 'telefonica o2'], icon: siO2 },
  openrouter: { contains: ['openai', 'chatgpt', 'chat gpt', 'openrouter'], icon: siOpenrouter },
  paramountplus: { contains: ['paramount+', 'paramount plus'], icon: siParamountplus },
  patreon: { contains: ['patreon'], icon: siPatreon },
  paypal: { contains: ['paypal'], icon: siPaypal },
  peloton: { contains: ['peloton'], icon: siPeloton },
  penny: { contains: ['penny markt', 'penny fil'], icon: siPenny },
  perplexity: { contains: ['perplexity'], icon: siPerplexity },
  picnic: { contains: ['picnic'], icon: siPicnic },
  playstation: { contains: ['playstation', 'sony psn', ' psn'], icon: siPlaystation },
  postmates: { contains: ['postmates'], icon: siPostmates },
  rakuten: { contains: ['rakuten'], icon: siRakuten },
  revolut: { contains: ['revolut'], icon: siRevolut },
  rewe: { contains: ['rewe'], icon: siRewe },
  rossmann: { contains: ['rossmann'], icon: siRossmann },
  ryanair: { contains: ['ryanair'], icon: siRyanair },
  shell: { contains: ['shell'], icon: siShell },
  southwestairlines: { contains: ['southwest airlines', 'southwest air'], icon: siSouthwestairlines },
  spotify: { contains: ['spotify'], icon: siSpotify },
  starbucks: { contains: ['starbucks', 'sbux'], icon: siStarbucks },
  starlingbank: { contains: ['starling'], icon: siStarlingbank },
  steam: { contains: ['steam'], icon: siSteam },
  stripe: { contains: ['stripe'], icon: siStripe },
  tacobell: { contains: ['taco bell', 'tacobell'], icon: siTacobell },
  target: { contains: ['target'], icon: siTarget },
  telefonica: { contains: ['telefónica', 'telefonica'], icon: siTelefonica },
  tesco: { contains: ['tesco'], icon: siTesco },
  tesla: { contains: ['tesla', 'supercharger'], icon: siTesla },
  tidal: { contains: ['tidal'], icon: siTidal },
  twitch: { contains: ['twitch'], icon: siTwitch },
  uber: { contains: ['uber'], icon: siUber },
  ubereats: { contains: ['uber eats', 'ubereats'], icon: siUbereats },
  uniqlo: { contains: ['uniqlo'], icon: siUniqlo },
  unitedairlines: { contains: ['united airlines', 'united air'], icon: siUnitedairlines },
  venmo: { contains: ['venmo'], icon: siVenmo },
  verizon: { contains: ['verizon'], icon: siVerizon },
  vinted: { contains: ['vinted'], icon: siVinted },
  vodafone: { contains: ['vodafone'], icon: siVodafone },
  westernunion: { contains: ['western union'], icon: siWesternunion },
  wise: { contains: ['transferwise', 'wise.com', 'wise'], icon: siWise },
  youtube: { contains: ['youtube'], icon: siYoutube },
  zalando: { contains: ['zalando'], icon: siZalando },
  zelle: { contains: ['zelle'], icon: siZelle },
};

const MerchantsEntries = Object.entries(MerchantsMap);

function normalizeForMatch(s: string): string {
  return s.toLowerCase().trim();
}

export function inferMerchantLogoSlug({ merchant_name, note }: InferInput): string | null {
  if (!merchant_name?.length && !note?.length) return null;
  const sources = [normalizeForMatch(merchant_name ?? ''), normalizeForMatch(note ?? '')];

  for (const source of sources) {
    if (!source) continue;
    for (const [slug, value] of MerchantsEntries) {
      for (const needle of value.contains) {
        if (source.includes(needle)) return slug;
      }
    }
  }
  return null;
}

export function getIconBySlug(slug: string): SimpleIcon | undefined {
  return MerchantsMap[slug]?.icon;
}
